// AUTO-GENERATED from the frontend's src/config/categories.ts via a one-time
// programmatic port (see chat history) - do not hand-edit the data below.
// If the frontend's taxonomy changes, re-run the same port rather than editing
// this file by hand, to avoid the two trees silently drifting apart.
//
// Top-level category maps 1:1 to the Prisma AuctionCategory enum via a plain
// .toUpperCase() / .toLowerCase() transform (frontend values are already
// snake_case, e.g. 'jewelry_watches' <-> 'JEWELRY_WATCHES') - see
// listings.constants.ts. subCategory/subSubCategory are validated against
// this tree but stored as plain strings, matching the frontend's own values
// exactly with no case transform needed.

import { AuctionCategory } from '@prisma/client';

export const CATEGORY_MIN_PRICE: Record<AuctionCategory, number> = {
  ELECTRONICS: 2500,
  ART_COLLECTIBLES: 500,
  FASHION: 500,
  JEWELRY_WATCHES: 500,
  HOME_GARDEN: 500,
  SPORTS: 500,
  STATIONERY_OFFICE: 300,
};

/** category (backend enum) -> valid subCategory string values */
export const VALID_SUBCATEGORIES: Record<AuctionCategory, string[]> = {
  ELECTRONICS: [
    'mobile_tablets',
    'computers',
    'cameras',
    'audio',
    'televisions',
    'gaming',
    'wearable_technology',
    'smart_home',
    'electronic_accessories',
  ],
  ART_COLLECTIBLES: [
    'paintings',
    'prints_posters',
    'photography',
    'sculptures',
    'coins_currency',
    'stamps',
    'memorabilia',
    'collectible_cards',
    'figurines_models',
    'musical_collectibles',
  ],
  FASHION: [
    'mens_clothing',
    'womens_clothing',
    'kids_clothing',
    'footwear',
    'bags',
    'wallets_belts',
    'sunglasses',
    'fashion_accessories',
  ],
  JEWELRY_WATCHES: [
    'fine_jewelry',
    'fashion_jewelry',
    'rings',
    'necklaces',
    'bracelets',
    'earrings',
    'mens_watches',
    'womens_watches',
    'smartwatches',
    'watch_accessories',
  ],
  HOME_GARDEN: [
    'furniture',
    'home_decor',
    'kitchen_dining',
    'home_appliances',
    'lighting',
    'garden_outdoor',
    'tools_hardware',
    'storage_organization',
  ],
  SPORTS: [
    'cricket',
    'football',
    'badminton',
    'tennis',
    'fitness',
    'cycling',
    'running',
    'outdoor_adventure',
    'sports_memorabilia',
    'sports_equipment',
  ],
  STATIONERY_OFFICE: [
    'writing',
    'notebooks_journals',
    'school_supplies',
    'art_drawing',
    'office_supplies',
    'desk_accessories',
    'paper_products',
    'bags_cases',
    'books_study',
  ],
};

/** subCategory string value -> valid subSubCategory string values */
export const VALID_SUBSUBCATEGORIES: Record<string, string[]> = {
  mobile_tablets: ['smartphones', 'tablets', 'e_readers', 'feature_phones'],
  computers: ['laptops', 'desktop_pcs', 'monitors', 'keyboards', 'mice', 'webcams'],
  cameras: [
    'dslr',
    'mirrorless',
    'point_shoot',
    'action_cameras',
    'camera_lenses',
    'camera_accessories',
  ],
  audio: ['headphones', 'earbuds', 'speakers', 'soundbars', 'microphones', 'amplifiers'],
  televisions: ['smart_tvs', 'led_tvs', 'projectors', 'streaming_devices', 'media_players'],
  gaming: [
    'gaming_consoles',
    'handheld_consoles',
    'controllers',
    'gaming_headsets',
    'gaming_accessories',
  ],
  wearable_technology: ['smartwatches', 'fitness_trackers', 'smart_bands', 'vr_headsets'],
  smart_home: ['smart_lights', 'smart_speakers', 'smart_cameras', 'smart_plugs', 'smart_sensors'],
  electronic_accessories: ['chargers', 'power_banks', 'cables', 'adapters', 'storage_devices'],
  paintings: ['oil_paintings', 'acrylic_paintings', 'watercolor_paintings', 'mixed_media'],
  prints_posters: ['art_prints', 'vintage_posters', 'movie_posters', 'music_posters'],
  photography: ['fine_art_photography', 'vintage_photographs', 'signed_photographs'],
  sculptures: ['metal_sculptures', 'wood_sculptures', 'stone_sculptures', 'ceramic_sculptures'],
  coins_currency: ['indian_coins', 'foreign_coins', 'commemorative_coins', 'banknotes'],
  stamps: ['indian_stamps', 'foreign_stamps', 'commemorative_stamps', 'stamp_collections'],
  memorabilia: [
    'celebrity_memorabilia',
    'movie_memorabilia',
    'music_memorabilia',
    'historical_memorabilia',
  ],
  collectible_cards: ['trading_cards', 'sports_cards', 'game_cards', 'collectible_card_sets'],
  figurines_models: ['action_figures', 'model_cars', 'miniatures', 'collectible_figures'],
  musical_collectibles: [
    'vinyl_records',
    'vintage_instruments',
    'signed_music_items',
    'music_merchandise',
  ],
  mens_clothing: [
    'shirts',
    't_shirts',
    'jackets',
    'jeans_trousers',
    'ethnic_wear',
    'suits_blazers',
  ],
  womens_clothing: [
    'dresses',
    'tops',
    'jeans_trousers_women',
    'ethnic_wear_women',
    'jackets_women',
    'sarees',
  ],
  kids_clothing: ['boys_clothing', 'girls_clothing', 'kids_ethnic_wear', 'kids_outerwear'],
  footwear: ['sneakers', 'sports_shoes', 'formal_shoes', 'boots', 'sandals', 'heels'],
  bags: ['backpacks', 'handbags', 'laptop_bags', 'duffle_bags', 'travel_bags'],
  wallets_belts: ['wallets', 'card_holders', 'belts'],
  sunglasses: ['aviator', 'wayfarer', 'round_sunglasses', 'sport_sunglasses'],
  fashion_accessories: ['scarves', 'caps_hats', 'ties', 'fashion_jewelry', 'hair_accessories'],
  fine_jewelry: ['gold_jewelry', 'silver_jewelry', 'diamond_jewelry', 'gemstone_jewelry'],
  fashion_jewelry: ['costume_jewelry', 'beaded_jewelry', 'handmade_jewelry'],
  rings: ['engagement_rings', 'fashion_rings', 'gemstone_rings'],
  necklaces: ['pendant_necklaces', 'chain_necklaces', 'statement_necklaces'],
  bracelets: ['chain_bracelets', 'charm_bracelets', 'bangles'],
  earrings: ['stud_earrings', 'hoop_earrings', 'drop_earrings'],
  mens_watches: ['mechanical_watches', 'automatic_watches', 'quartz_watches', 'luxury_watches'],
  womens_watches: ['analog_watches', 'dress_watches', 'luxury_womens_watches'],
  smartwatches: ['fitness_smartwatches', 'premium_smartwatches', 'everyday_smartwatches'],
  watch_accessories: ['watch_straps', 'watch_boxes', 'watch_winders'],
  furniture: ['chairs', 'tables', 'desks', 'sofas', 'beds', 'shelves'],
  home_decor: ['wall_decor', 'decorative_objects', 'mirrors', 'rugs', 'cushions'],
  kitchen_dining: ['cookware', 'dinnerware', 'glassware', 'cutlery', 'kitchen_tools'],
  home_appliances: ['fans', 'vacuum_cleaners', 'air_purifiers', 'heaters', 'irons'],
  lighting: ['table_lamps', 'floor_lamps', 'ceiling_lights', 'decorative_lighting'],
  garden_outdoor: ['garden_tools', 'planters', 'outdoor_furniture', 'garden_decor'],
  tools_hardware: ['hand_tools', 'power_tools', 'tool_sets', 'hardware'],
  storage_organization: ['storage_boxes', 'cabinets', 'organizers', 'shelving'],
  cricket: ['cricket_bats', 'cricket_balls', 'cricket_kits', 'cricket_protection'],
  football: ['football_balls', 'football_boots', 'football_kits', 'football_equipment'],
  badminton: [
    'badminton_rackets',
    'badminton_shuttlecocks',
    'badminton_kits',
    'badminton_accessories',
  ],
  tennis: ['tennis_rackets', 'tennis_balls', 'tennis_bags', 'tennis_accessories'],
  fitness: ['dumbbells', 'kettlebells', 'exercise_equipment', 'fitness_accessories'],
  cycling: ['cycling_helmets', 'cycling_jerseys', 'cycling_shoes', 'cycling_accessories'],
  running: ['running_shoes', 'running_wear', 'running_accessories', 'running_electronics'],
  outdoor_adventure: ['camping_gear', 'hiking_gear', 'trekking_gear', 'adventure_accessories'],
  sports_memorabilia: [
    'signed_jerseys',
    'signed_equipment',
    'sports_photos',
    'sports_collectibles',
  ],
  sports_equipment: ['training_equipment', 'protective_gear', 'sports_bags', 'sports_accessories'],
  writing: ['ball_pens', 'gel_pens', 'fountain_pens', 'pencils', 'mechanical_pencils', 'markers'],
  notebooks_journals: ['notebooks', 'journals', 'diaries', 'sketchbooks'],
  school_supplies: ['school_kits', 'geometry_sets', 'erasers_sharpeners', 'school_organizers'],
  art_drawing: [
    'sketching_pencils',
    'color_pencils',
    'crayons',
    'watercolors',
    'acrylic_colors',
    'drawing_tools',
  ],
  office_supplies: ['folders_files', 'staplers', 'paper_clips', 'labels', 'calculators'],
  desk_accessories: [
    'pen_holders',
    'desk_organizers',
    'desk_calendars',
    'mouse_pads',
    'desk_decor',
  ],
  paper_products: ['copy_paper', 'colored_paper', 'craft_paper', 'sticky_notes', 'envelopes'],
  bags_cases: ['pencil_cases', 'document_cases', 'stationery_pouches', 'school_bags'],
  books_study: [
    'textbooks',
    'reference_books',
    'competitive_exam_books',
    'study_guides',
    'educational_material',
  ],
};
